export const testConfig = {
    prod: 'https://www.plentific.com/en-gb/',
    qa: `http://qa.plentific.com/`,
    dev: ``,
    qaApi: ``,
    devApi: ``,
    businessEmail:'kaan.yurtsever@plentific.com',
    firstName: 'Kaan',
    lastName: 'Yurtsever',
    countryPhone: 'TR',
    countryPhoneWithoutCode: '5555555555',
    organisationName: 'Plentific',
    jobTitle: 'Software Test Engineer',
    phoneNumber: '+905555555555',
    locationOfProp: 'United States',
    areaOfFocus: 'Student Housing',
    propUnderMngmnt: '500 - 999',
    username: ``,
    password: ``,
    waitForElement: 120000,
    dbUsername: ``,
    dbPassword: ``,
    dbServerName: ``,
    dbPort: ``,
    dbName: ``
}