name: CI/CD

on:
   push:
     branches:
     - main
jobs:
   e2e-tests:
     runs-on: windows-latest # or macos-latest, ubuntu-latest
 
     steps:
       - uses: actions/checkout@v2
       
       - name: Install Node.js
         uses: actions/setup-node@v3
         with:
            node-version: lts/*
       
       - uses: microsoft/playwright-github-action@v1
       
       - name: Install dependencies
         run: npm install
         
       - name: Install browsers
         run: npx playwright install
         
       - name: Run tests
         run: npm run github-action
         
       - name: push artifacts
         if: always()
         uses: actions/upload-artifact@v2
         with:
           name: my-artifact
           path: |
            playwright-report/**
            test-results/**
           if-no-file-found: error
           retention-days: 60
         
  
